Fixes
MPLauncher/MPLauncher pull request #1
Opened 2017-07-22 19:18 UTC by gabixdev

very small changes

2017-07-22 19:23 UTC, kacperduras requested changes

2017-07-22 19:23 UTC, kacperduras commented on src/main/java/pl/mplauncher/launcher/MPLauncherApp.java
> -        System.setOut(new PrintStream(new Log4j2OutputStream(bootstrapLogger, Level.INFO)));
why?

2017-07-22 19:23 UTC, kacperduras commented on src/main/java/pl/mplauncher/launcher/MPLauncherApp.java
> +        // logs should be printed only on one stream...
unnecessary comment.

2017-07-22 19:23 UTC, kacperduras commented on src/main/java/pl/mplauncher/launcher/MPLauncherApp.java
> +                                                "Version 2.0."); // why warn?
same.

2017-07-22 19:33 UTC, gabixdev commented
@kacperduras done

2017-07-22 19:34 UTC, kacperduras commented
@gabixdev 
```
System.setErr(new PrintStream(new Log4j2OutputStream(bootstrapLogger, Level.INFO)));
System.setErr(new PrintStream(new Log4j2OutputStream(bootstrapLogger, Level.ERROR)));
```

I don't think so.

2017-07-22 19:35 UTC, gabixdev commented
i have noticed that, now fixing xD

2017-07-22 19:55 UTC, kacperduras requested changes

2017-07-22 19:55 UTC, kacperduras commented on src/main/java/pl/mplauncher/launcher/MPLauncherApp.java
> +        System.setErr(new PrintStream(new Log4j2OutputStream(bootstrapLogger, Level.INFO, "[STDERR] ")));
All prefixes should be configured by a .xml file.

2017-07-23 10:51 UTC, kacperduras commented
I close, it's a shame to talk.

2017-07-23 10:51 UTC, closed without merging